name: Build KoosReplay

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  build-windows:
    name: Build Windows App
    runs-on: windows-latest

    permissions:
      contents: read

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Install dependencies
        run: npm install

      - name: Install ImageMagick
        shell: pwsh
        run: |
          choco install imagemagick -y --no-progress

      - name: Generate icon
        shell: pwsh
        run: |
          New-Item `
            -ItemType Directory `
            -Force `
            -Path "src-tauri/icons"

          magick convert `
            "src-tauri/icons/koosreplay.svg" `
            -background none `
            -define icon:auto-resize=256,128,64,48,32,16 `
            "src-tauri/icons/icon.ico"

          if (!(Test-Path "src-tauri/icons/icon.ico")) {
            throw "icon.ico was not generated."
          }

      - name: Download FFmpeg
        shell: pwsh
        run: |
          $url = "https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip"

          $zip = "$env:RUNNER_TEMP\ffmpeg.zip"

          $extract = "$env:RUNNER_TEMP\ffmpeg"

          Invoke-WebRequest `
            -Uri $url `
            -OutFile $zip

          Expand-Archive `
            -Path $zip `
            -DestinationPath $extract `
            -Force

          $ffmpeg = Get-ChildItem `
            -Path $extract `
            -Filter "ffmpeg.exe" `
            -Recurse |
            Select-Object -First 1

          if (-not $ffmpeg) {
            throw "ffmpeg.exe was not found."
          }

          New-Item `
            -ItemType Directory `
            -Force `
            -Path "src-tauri/bin"

          Copy-Item `
            $ffmpeg.FullName `
            "src-tauri/bin/ffmpeg.exe"

      - name: Verify FFmpeg
        shell: pwsh
        run: |
          if (!(Test-Path "src-tauri/bin/ffmpeg.exe")) {
            throw "FFmpeg was not copied."
          }

          & "src-tauri/bin/ffmpeg.exe" -version

      - name: Build KoosReplay
        run: npm run tauri build

      - name: Upload Windows installers
        uses: actions/upload-artifact@v4
        with:
          name: KoosReplay-Windows
          path: |
            src-tauri/target/release/bundle/nsis/*.exe
            src-tauri/target/release/bundle/msi/*.msi
